use smallest filtersize for initial buffer
teragrep/dpf_03 pull request #47
Opened 2024-11-05 07:45 UTC by elliVM

Replace small hard coded initial filter and use the smallest filter size from map.

- If different size filters come into merge return the larger one (case when initial filter size is updated)
- Add testing for filter size selection and missing estimate value

2024-11-05 13:16 UTC, elliVM commented
rebased to main

2024-11-06 11:28 UTC, 51-code requested changes

2024-11-06 11:28 UTC, 51-code commented on src/main/scala/com/teragrep/functions/dpf_03/BloomFilterAggregator.scala
> +      return if (ours.bitSize() < their.bitSize()) their else ours
Just one point of return could be clearer by providing a variable for the eventually returned BloomFilter, or just returning the value from an if-else.

2024-11-06 13:39 UTC, elliVM commented on src/main/scala/com/teragrep/functions/dpf_03/BloomFilterAggregator.scala
> +      return if (ours.bitSize() < their.bitSize()) their else ours
refactored to a single return point

2024-11-07 07:01 UTC, 51-code approved these changes
lgtm

2026-02-26 08:49 UTC, elliVM commented
not required

2026-02-26 08:49 UTC, closed without merging